openapi: 3.0.3
info:
  title: Time Components
  description: Reusable Open API Components Related to Time Domain Objects
  version: 1.0.0
paths: {}
components:
  schemas:
    DateTime:
      type: string
      format: date-time
      pattern: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:Z|[\+-]\d{2}:\d{2})$'
      description: >
        Date and time with timezone offset in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339)
        `date-time` format, without fractional seconds, based on the ISO 8601 standard,
        e.g. "YYYY-MM-DDThh:mm:ss+00:00"
      example: "2021-11-12T16:31:58-06:00"

    Date:
      type: string
      format: date
      pattern: '^\d{4}-\d{2}-\d{2}$'
      description: >
        Calendar date value expressed in [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339)
        `full-date` format, based on the ISO 8601 standard, e.g. "YYYY-MM-DD",
      example: "2021-08-31"

    Month:
      type: string
      pattern: '^\d{4}-\d{2}$'
      description: >
        Month and Year values expressed as a string in "YYYY-MM" format, as
        permitted by ISO 8601, and equivalent to `date-fullyear "-" date-month`
        in terms of the syntax defined by [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339).
      example: "2021-09"

    Year:
      type: integer
      description: Year value expressed as a integer.
      example: 2021

    DateAdded:
      allOf:
        - $ref: "#/components/schemas/DateTime"
        - title: Date and time the resource was originally persisted to the database.

    DateUpdated:
      allOf:
        - $ref: "#/components/schemas/DateTime"
        - title: Date and time the resource was last updated.
